server:
  port: 8802

spring:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userDB
    username: sauravS
    password: saurav@simmi

  jpa:
    hibernate:
      ddl-auto: update
    database: MYSQL